# Site
repository: sungjaegh/sungjaegh.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 정성재
title: 백엔드 개발자
email: dtc13579@gmail.com
website: https://velog.io/@dtc1674/posts

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: SungjaeGH
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jsung_jae
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links

# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  
  3년 차 백엔드 개발자로 아크데이타에서 DB 데이터 복제 솔루션을 설계/개발/운영하였으며,
  
  주로 솔루션 내 서버 모듈인 Agent 모듈 통신을 위한 <u>REST API들을 개발/유지보수</u>하였습니다.
  
  <br>
  
  <mark><b>동료들과 원활한 커뮤니케이션을 통해 협업</b></mark>하는 것을 좋아합니다.
  * 사람을 좋아하는 성향이라 어떠한 환경에 있던 주변 사람들과 원만한 관계를 유지하면서 지냅니다.
  * <u>동료들의 의견을 경청하고 적극적으로 활용하려는 태도</u>로 서버와 모듈 간의 UDS 통신 이슈를 해결했던 경험이 있습니다.
  
  코드의 품질을 높히기 위한 <mark><b>클린 코드</b></mark>에 관심이 많습니다.
  * 혼자만 이해하는 코드를 짜는 것은 프로그램의 성능저하 뿐만 아니라 동료들과의 협업에도 피해를 준다고 생각합니다.
  * 레거시 코드를 리팩토링하면서 담당 모듈의 성능을 <u>100% 상승</u>시켰던 경험이 있습니다.
  
  <mark><b>배움을 통해 지속적으로 발전</b></mark>하는 것을 좋아합니다.
  * <u>스터디</u>를 통해 동료들과 지식을 공유하고, 부족한 부분을 보완하며 함께 성장하길 원합니다.

content:
  #  - title: Projects # Title for the section
  #    layout: list # Type of content section (list/text)
  #    content:
  #      - layout: top-middle
  #        title: Super awesome project
  #        link: github.com/sproogen
  #        # link_text: Project Website
  #        additional_links:
  #          - title:  sproogen/modern-resume-theme
  #            icon: fab fa-github
  #            url: github.com/sproogen/modern-resume-theme
  #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          #   icon: fab fa-github
  #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #        quote: >
  #          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #        description: | # this will include new lines to allow paragraphs
  #          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Languages & Frameworks
        description: |
          Java, C  
          Spring Boot, JPA, QueryDSL  
          REST API, JWT, Spring Security  

      - layout: left
        title: Infrastructure & Tools
        description: |
          MySQL, Oracle, Linux  
          Docker, AWS EC2/S3  
          Git, GitHub, GitLab, Jira  

      - layout: left
        title: Practices & Collaboration
        description: |
          테스트 코드 (JUnit5, Mockito)  
          Swagger, REST Docs  
          애자일 개발, 코드 리뷰, Notion

  - title: Careers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 아크데이타
        link: http://www.iarkdata.com/main
        # link_text: boringcompany.com
        sub_title: 시스템 백엔드 개발자
        caption: 2021.03 ~ 2023.09
        quote: >
          실시간 이기종 Database 복제 솔루션 운영/개발

        description: | # this will include new lines to allow paragraphs
          [Ark for CDC 솔루션 운영](https://jsungj.notion.site/Ark-for-CDC-54ec3b62ca7348ba80128f95995d5197)
            * 담당 모듈(Agent, Pmon, Mgr) 내 발생하는 <u>이슈 90% 해결</u>
            * 담당 모듈(Agent, Pmon, Mgr)의 레거시 코드 리팩토링으로 <u>성능 100% 상승</u>
            * Make 빌드 방식 개선으로 <u>빌드 속도 6배 단축</u>
            * Agent 서버의 통신 API 테스트 방식 개선으로 <u>테스트 수행 시간 3배 단축</u>
          
          [Ark for CDC v2.1 개발 및 테스트](https://jsungj.notion.site/ArkCDC-v2-1-9490f05bb0f8453883e1b0f9eef56a70)
            * <u>약 10억건</u>의 우리종합금융 서버의 <u>1:5 데이터 초기 복제</u> 및 <u>실시간 데이터 복제</u> 환경 구축
            * Agent 서버의 <u>통신 API 처리 속도 6배 단축</u>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 프로그래머스 데브코스
        caption: 2024.11 ~ 2025.04
        sub_title: (주)그렙 / 프로그래머스
        quote: >
          Java & 클라우드 기반 백엔드 개발 심화 교육 과정
        description: | # this will include new lines to allow paragraphs
          * Java 문법 및 객체지향 설계 원칙 학습, REST API 구현 등 실무 위주의 백엔드 개발 교육  
          * Spring MVC, Spring Security, JWT, OAuth2 기반 인증/인가, Swagger 및 REST Docs를 활용한 API 문서화 실습  
          * MySQL 중심 DB 설계 및 정규화, Docker, AWS 기반 배포 및 CI/CD 파이프라인 개념 학습  
          * Git/GitHub, Jira를 활용한 팀 프로젝트 경험 (CRUD 프로젝트, REST API 프로젝트, 최종 서비스 구현)

      - layout: left
        title: 성능 극대화를 위한 SQL튜닝 및 사례 연구
        caption: 2021.12 ~ 2021.12
        sub_title: 재단법인대구디지털혁신진흥원
        quote: >
          Oracle 기반의 SQL 튜닝 교육
        description: | # this will include new lines to allow paragraphs
          * DB 복제 솔루션 개발/유지보수에 필요한 Oracle 아키텍처 이해의 필요성을 느껴 참석
          * 기본적인 RDBMS 아키텍처, 인덱스, 실행 계획 교육

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
